import type { NextPage } from "next";
import Head from "next/head";
import Shared from "../components/Shared";

const Home: NextPage = () => {
  const Home = () => {
    return <h1>Home</h1>;
  };
  return (
    <div>
      <Head>
        <title>X-Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Shared>
          <Home />
        </Shared>
      </div>
    </div>
  );
};

export default Home;
