"use client";

import type { NextPage } from "next";
import Head from "next/head";
import Shared from "../components/Shared";
import { styled } from "@mui/material/styles";
import BarChartIcon from "@mui/icons-material/BarChart";
import Table from "@mui/material/Table";
import TableBody from "@mui/material/TableBody";
import MuiTableCell from "@mui/material/TableCell";
import TableContainer from "@mui/material/TableContainer";
import TableRow from "@mui/material/TableRow";
import Image from "next/image";

const TableCell = styled(MuiTableCell)({
  borderBottom: "none",
});

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>X-Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Shared tab="home">
          <div className="bg-gray-100 p-4 md:p-8">
            {/* Filter Buttons */}
            <div className="flex justify-center md:justify-end lg:mr-[5%]">
              <div className="flex gap-2 flex-wrap">
                {["All", "1M", "6M", "1Y", "YTD"].map((item) => (
                  <div
                    key={item}
                    className="border rounded-xl px-4 py-1 cursor-pointer hover:bg-[#14EA83] hover:text-white text-sm md:text-base"
                  >
                    {item}
                  </div>
                ))}
              </div>
            </div>

            {/* Statistics Cards */}
            <div className="mt-6 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 max-w-7xl mx-auto">
              {[
                "Deposited",
                "Withdraws",
                "Sent",
                "Received",
                "Number of users",
                "Successful",
                "Pending transactions",
                "Failed transactions",
              ].map((title) => (
                <div
                  key={title}
                  className="flex items-center gap-4 p-4 bg-white rounded-xl shadow w-full max-w-sm mx-auto lg:w-[21%]"
                >
                  <div className="text-[#14EA83]">
                    <BarChartIcon />
                  </div>
                  <div>
                    <div className="text-xs text-gray-500">{title}</div>
                    <div className="text-lg font-semibold">9898</div>
                  </div>
                </div>
              ))}
            </div>

            {/* Recent Transactions Table */}
            <div className="bg-white w-full max-w-5xl mx-auto mt-10 p-6 rounded-xl overflow-x-auto">
              <p className="text-lg font-semibold pb-4">Recent Transactions</p>
              <TableContainer>
                <Table
                  sx={{ minWidth: 650 }}
                  size="small"
                  aria-label="simple table"
                >
                  <TableBody>
                    {[
                      {
                        src: "/images/bitcoin.png",
                        name: "Bitcoin",
                        status: "Completed",
                        color: "text-green-400",
                      },
                      {
                        src: "/images/ethereum.png",
                        name: "Ethereum",
                        status: "Pending",
                        color: "text-gray-400",
                      },
                      {
                        src: "/images/litecoin.png",
                        name: "LTC",
                        status: "Completed",
                        color: "text-green-400",
                      },
                    ].map((item, index) => (
                      <TableRow key={index} className="whitespace-nowrap">
                        <TableCell>
                          <Image
                            src={item.src}
                            alt={item.name}
                            width={40}
                            height={40}
                          />
                        </TableCell>
                        <TableCell className="text-xs text-gray-600">
                          {item.name}
                        </TableCell>
                        <TableCell className="text-xs text-gray-600">
                          10:45:00 AM
                        </TableCell>
                        <TableCell className="text-xs text-gray-600">
                          +154.00$
                        </TableCell>
                        <TableCell className={`text-xs ${item.color}`}>
                          {item.status}
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </TableContainer>
            </div>
          </div>
        </Shared>
      </div>
    </div>
  );
};

export default Home;
